CREATE TABLE UDR_ST_CRLP
(
AGGREG_INFO_AGGREG_PURPOSE VARCHAR2(1),
AGGREG_INFO_AGG_TRANS_ID INTEGER,
AGGREG_INFO_APPLIED_PACK_ID INTEGER,
AGGREG_INFO_REC_COUNTER INTEGER,
AGGREG_INFO_SUMMARY_ID INTEGER,
ALT_RATED_AMOUNT FLOAT,
ALT_RATED_CURRENCY INTEGER,
ALT_TARIFF_CLICKS_VOLUME FLOAT,
ALT_TMCODE INTEGER,
AN_PACK_AN_PACKAGE_ID_LIST VARCHAR2(64),
AN_PACK_ORIG_AN_PACK_ID_LIST VARCHAR2(64),
BAL_AUDIT_DATA_ACCOUNT_ID INTEGER,
BAL_AUDIT_DATA_ACCOUNT_TYPE VARCHAR2(1),
BAL_AUDIT_DATA_ACCOUNT_TYPE_ID INTEGER,
BAL_AUDIT_DAT_BALANCE_ACCUM FLOAT,
BAL_AUDIT_DAT_BALANCE_PROD_ID INTEGER,
BAL_AUDIT_DAT_BALANCE_TYPE INTEGER,
BAL_AUDIT_DAT_BAL_AFTER_CHG FLOAT,
BAL_AUDIT_DAT_BAL_BEFORE_CHG FLOAT,
BAL_AUDIT_DAT_BUNDL_PROD_ID INTEGER,
BAL_AUDIT_DAT_CONTRACT_ID INTEGER,
BAL_AUDIT_DAT_OFFER_SEQNO INTEGER,
BAL_AUDIT_DAT_OFFER_SNCODE INTEGER,
BAL_AUDIT_DAT_PREP_CREDIT_IND INTEGER,
BAL_AUDIT_DAT_PURCHASE_SEQ_NO INTEGER,
BAL_AUDIT_DAT_SHACC_PACKID INTEGER,
BAL_AUDIT_DAT_USER_PROFILE_ID INTEGER,
BOP_INFO_BOP_PACKAGE_ID INTEGER,
BOP_INFO_BOP_PACKAGE_PKEY VARCHAR2(10),
BOP_INFO_BOP_PACKAGE_VERSION INTEGER,
BOP_INFO_DETAIL_BILLED_IND INTEGER,
BOP_INFO_DETAIL_BOP_ALTERN_IND INTEGER,
BOP_INFO_DETAIL_CONTRACTED_IND INTEGER,
BOP_INFO_DETAIL_SEQUENCE_RP INTEGER,
BOP_INFO_DETAIL_SEQUENCE_SP INTEGER,
BOP_TARIFF_INFO_DAY_CATCODE VARCHAR2(2),
BOP_TARIFF_INFO_EGCODE INTEGER,
BOP_TARIFF_INFO_EGVERSION INTEGER,
BOP_TARIFF_INFO_GVCODE INTEGER,
BOP_TARIFF_INFO_RPCODE INTEGER,
BOP_TARIFF_INFO_RPVERSION INTEGER,
BOP_TARIFF_INFO_SNCODE INTEGER,
BOP_TARIFF_INFO_SPCODE INTEGER,
BOP_TARIFF_INFO_TIME_BAND_CODE VARCHAR2(2),
BOP_TARIFF_INFO_TMCODE INTEGER,
BOP_TARIFF_INFO_TMVERSION INTEGER,
BOP_TARIFF_INFO_TM_USED_TYPE INTEGER,
BOP_TARIFF_INFO_TWCODE INTEGER,
BOP_TARIFF_INFO_USAGE_IND INTEGER,
BOP_TARIFF_INFO_ZNCODE INTEGER,
BOP_TARIFF_INFO_ZPCODE INTEGER,
BPARTN_SUM_INFO_TIME_SLICE_LB INTEGER,
BPARTN_SUM_INFO_TIME_SLICE_RB INTEGER,
BUNDLE_INFO_BUNDLE_PURCHASE_ID VARCHAR2(15),
BUNDLE_INFO_BUNDLE_PURCH_IND INTEGER,
BUNDLE_INFO_CONTRACT_ID INTEGER,
BUNDLE_INFO_PURCHASE_SEQ_NO INTEGER,
BUNDLE_INFO_SEQUENCE_NUMBER INTEGER,
BUNDLE_INFO_SNCODE INTEGER,
BUNDLE_INFO_STATE VARCHAR2(1),
BUNDLE_INFO_TERMINATION DATE,
BUNDLE_INFO_USER_PROFILE_ID INTEGER,
BUNDLE_INFO_VALID_FROM DATE,
BUNDLE_INFO_VALID_TO DATE,
BUNDLE_INFO_VERSION INTEGER,
BUNDLE_USG_BUNDLE_COVERED_USG VARCHAR2(1),
BUSINESS_INFO_BS_ID INTEGER,
BUSINESS_INFO_BS_VERSION INTEGER,
BUSINESS_INFO_CHARGE_ITEM_ID INTEGER,
BUSINESS_INFO_CHARGE_PARTY_ID INTEGER,
BUSINESS_INFO_C_P_FIELD_REF INTEGER,
BUSINESS_INFO_O_P_FIELD_REF INTEGER,
BUSINESS_INFO_PRE_BS_ID INTEGER,
BUSINESS_INFO_PRE_BS_VERSION INTEGER,
BUS_PARTNER_INFO_TAX_MODE INTEGER,
CALL_DEST VARCHAR2(2),
CALL_TYPE INTEGER,
CAMEL_DEST_ADDR_USER_PROF_ID INTEGER,
CAMEL_MSC_ADDRESS VARCHAR2(100),
CAMEL_MSC_ADDR_USER_PROF_ID INTEGER,
CAMEL_REFERENCE_NUMBER VARCHAR2(16),
CAMEL_SRV_ADDR_USER_PROF_ID INTEGER,
CHARGE_INFO_CASH_FLOW_DIRECT INTEGER,
CHARGE_INFO_DISABLE_TAX INTEGER,
CHARGING_CHARACTERISTICS VARCHAR2(1),
CONSUMER_INFO_ADDRESS VARCHAR2(100),
CONSUMER_INFO_CONTRACT_ID INTEGER,
CONSUMER_INFO_NUMBERING_PLAN INTEGER,
CONTENT_ADVISED_CHARGE_IND INTEGER,
CONTENT_AUTHORISATION_CODE VARCHAR2(20),
CONTENT_CONTENT_CHARGING_POINT VARCHAR2(1),
CONTENT_CONTRACT_PKEY VARCHAR2(30),
CONTENT_DESC_SUPPRESS INTEGER,
CONTENT_PAID_IND INTEGER,
CONTENT_PAYMENT_METHOD INTEGER,
CONTENT_PROVIDER_ADDRESS VARCHAR2(100),
CONTENT_PROVIDER_CARRIER_CODE INTEGER,
CONTENT_PROVIDER_CLIR INTEGER,
CONTENT_PROVIDER_IAC VARCHAR2(10),
CONTENT_PROVIDER_MODIF_IND INTEGER,
CONTENT_PROVIDER_NETWORK_CODE INTEGER,
CONTENT_PROVID_DYNAMIC_ADDRESS INTEGER,
CONTENT_PROVID_LOCAL_PREF_LEN INTEGER,
CONTENT_PROVID_NUMBERING_PLAN INTEGER,
CONTENT_PROVID_OTHER_LOCATION VARCHAR2(50),
CONTENT_PROVID_TYPE_OF_NUMBER INTEGER,
CONTENT_PROVID_USER_PROFILE_ID INTEGER,
CONTENT_REFUND_IND INTEGER,
CONTENT_SHORT_DESC VARCHAR2(24),
CONTENT_TRANSACTION_ID VARCHAR2(20),
CONTROL_DATA_RECORD_AGE INTEGER,
CUG_INFO_CUG_ID INTEGER,
CUG_INFO_CUG_INDEX INTEGER,
CUSTOMER_INFO_CONTRACT_TYPE_ID INTEGER,
CUSTOMER_INFO_CONTRAGGRPACK_ID INTEGER,
CUSTOMER_INFO_RECO_IND INTEGER,
CUST_INFO_ADDRESS VARCHAR2(100),
CUST_INFO_ALTERNATE_TMCODE INTEGER,
CUST_INFO_AN_PACKAGE_ID_LIST VARCHAR2(64),
CUST_INFO_BILL_CYCLE VARCHAR2(2),
CUST_INFO_BU_ADDRESS VARCHAR2(100),
CUST_INFO_BU_NUMBERING_PLAN INTEGER,
CUST_INFO_CHARGING_ENGINE INTEGER,
CUST_INFO_CONTRACT_ID INTEGER,
CUST_INFO_CUSTOMER_ID INTEGER,
CUST_INFO_DELETE_AFTER_BILLING INTEGER,
CUST_INFO_DN_ID INTEGER,
CUST_INFO_MAIN_MSISDN VARCHAR2(65),
CUST_INFO_NUMBERING_PLAN INTEGER,
CUST_INFO_PORT_ID INTEGER,
CUST_INFO_SERV_BID_ID INTEGER,
CUST_INFO_SIM_NUMBER INTEGER,
CUST_INFO_SIM_SERNUMBER VARCHAR2(50),
CUST_INFO_SUBS_CODE INTEGER,
CUST_INFO_SUBS_TAG INTEGER,
CUST_INFO_USER_PROFILE_ID INTEGER,
DATA_VOLUME FLOAT,
DATA_VOLUME_UMCODE INTEGER,
DESC_PROD_USAGE_LONG_DESC VARCHAR2(500),
DESTINATION_FIELD_ID INTEGER,
DOWNLINK_VOLUME_UMCODE INTEGER,
DOWNLINK_VOLUME_VOLUME FLOAT,
DURATION_UMCODE INTEGER,
DURATION_VOLUME FLOAT,
ENTRY_DATE_OFFSET INTEGER,
ENTRY_DATE_TIMESTAMP DATE,
EVENT_INFO_EVENT_TYPE INTEGER,
EVENT_STATUS_INFO_MESSAGE_ID INTEGER,
EVENT_UMCODE INTEGER,
EVENT_VOLUME FLOAT,
EXPORT_FILE VARCHAR2(17),
EXT_BALANCE_AMNT_AMOUNT FLOAT,
FOLLOW_UP_CALL_TYPE INTEGER,
FOR_AMOUNT_AMOUNT FLOAT,
FOR_AMOUNT_CURRENCY INTEGER,
FOR_AMOUNT_GROSS_IND INTEGER,
FOR_AMOUNT_TAX FLOAT,
FOR_FREECHRG_AMOUNT FLOAT,
FOR_FREECHRG_CURRENCY INTEGER,
FOR_FREECHRG_GROSS_IND INTEGER,
FOR_FREECHRG_TAX FLOAT,
FREE_CHARGE_AMOUNT FLOAT,
FREE_CHARGE_AMOUNT_NON_RPC FLOAT,
FREE_CHARGE_CURRENCY INTEGER,
FREE_CHARGE_CURR_NON_RPC INTEGER,
FREE_CHARGE_GROSS_IND INTEGER,
FREE_CHARGE_GROSS_IND_NRPC INTEGER,
FREE_CHARGE_TAX FLOAT,
FREE_CHARGE_TAX_NRPC FLOAT,
FREE_CLICKS_UMCODE INTEGER,
FREE_CLICKS_VOLUME FLOAT,
FREE_RATED_VOLUME_UMCODE INTEGER,
FREE_RATED_VOLUME_VOLUME FLOAT,
FREE_ROUNDED_VOLUME_UMCODE INTEGER,
FREE_ROUNDED_VOLUME_VOLUME FLOAT,
FREE_UNITS_INFO_ACCOUNT_KEY INTEGER,
FREE_UNITS_INFO_ACCOUNT_ORIGIN VARCHAR2(1),
FREE_UNITS_INFO_ACC_HIST_ID INTEGER,
FREE_UNITS_INFO_APPL_METHOD VARCHAR2(1),
FREE_UNITS_INFO_CHG_RED_QUOTA VARCHAR2(1),
FREE_UNITS_INFO_DISCOUNT_RATE FLOAT,
FREE_UNITS_INFO_DISCOUNT_TYPE VARCHAR2(1),
FREE_UNITS_INFO_FREEUNITOPTION VARCHAR2(1),
FREE_UNITS_INFO_FUP_SEQ INTEGER,
FREE_UNITS_INFO_FU_PACK_ID INTEGER,
FREE_UNITS_INFO_PART_CREATOR VARCHAR2(1),
FREE_UNITS_INFO_PREVIOUS_SEQNO INTEGER,
FREE_UNITS_INFO_SEQNO INTEGER,
FREE_UNITS_INFO_VERSION INTEGER,
HOME_NETWORK_CODE INTEGER,
HSCSD_INFO_AIUR INTEGER,
HSCSD_INFO_CHANNELS_MAX INTEGER,
HSCSD_INFO_CHANNELS_USED INTEGER,
HSCSD_INFO_CODING_ACC INTEGER,
HSCSD_INFO_CODING_USED INTEGER,
HSCSD_INFO_FNUR INTEGER,
HSCSD_INFO_INIT_PARTY INTEGER,
IMP_PARTY1_ADDRESS VARCHAR2(100),
IMP_PARTY1_ALTERNATE_TMCODE INTEGER,
IMP_PARTY1_AN_PACKAGE_ID_LIST VARCHAR2(64),
IMP_PARTY1_BILL_CYCLE VARCHAR2(2),
IMP_PARTY1_NUMBERING_PLAN INTEGER,
IMP_PARTY1_USER_PROFILE_ID INTEGER,
IMP_PARTY2_ADDRESS VARCHAR2(100),
IMP_PARTY2_ALTERNATE_TMCODE INTEGER,
IMP_PARTY2_AN_PACKAGE_ID_LIST VARCHAR2(64),
IMP_PARTY2_BILL_CYCLE VARCHAR2(2),
IMP_PARTY2_NUMBERING_PLAN INTEGER,
IMP_PARTY2_USER_PROFILE_ID INTEGER,
IMP_PARTY3_ADDRESS VARCHAR2(100),
IMP_PARTY3_ALTERNATE_TMCODE INTEGER,
IMP_PARTY3_AN_PACKAGE_ID_LIST VARCHAR2(64),
IMP_PARTY3_BILL_CYCLE VARCHAR2(2),
IMP_PARTY3_NUMBERING_PLAN INTEGER,
IMP_PARTY3_USER_PROFILE_ID INTEGER,
IMP_PARTY4_ADDRESS VARCHAR2(100),
IMP_PARTY4_ALTERNATE_TMCODE INTEGER,
IMP_PARTY4_AN_PACKAGE_ID_LIST VARCHAR2(64),
IMP_PARTY4_BILL_CYCLE VARCHAR2(2),
IMP_PARTY4_NUMBERING_PLAN INTEGER,
IMP_PARTY4_PARENT_CONTRACT_ID INTEGER,
IMP_PARTY4_USER_PROFILE_ID INTEGER,
IMP_PARTY5_ADDRESS VARCHAR2(100),
IMP_PARTY5_ALTERNATE_TMCODE INTEGER,
IMP_PARTY5_AN_PACKAGE_ID_LIST VARCHAR2(64),
IMP_PARTY5_BILL_CYCLE VARCHAR2(2),
IMP_PARTY5_NUMBERING_PLAN INTEGER,
IMP_PARTY5_PARENT_CONTRACT_ID INTEGER,
IMP_PARTY5_USER_PROFILE_ID INTEGER,
INITIAL_START_TIME_TIMESTAMP DATE,
INITIAL_START_TIME_TIME_OFFSET INTEGER,
LCS_QOS_DELIV_HORIZONTAL_ACCUR INTEGER,
LCS_QOS_DELIV_TRACKING_FREQUEN INTEGER,
LCS_QOS_DELIV_TRACKING_PERIOD INTEGER,
LCS_QOS_DELIV_VERTICAL_ACCUR INTEGER,
LCS_QOS_INFO_AGE_OF_LOCATION INTEGER,
LCS_QOS_INFO_POSITION_METHOD INTEGER,
LCS_QOS_INFO_RESPONSE_TIME INTEGER,
LCS_QOS_INFO_RESPONSE_TIME_CAT INTEGER,
LCS_QOS_REQ_HORIZONTAL_ACCUR INTEGER,
LCS_QOS_REQ_TRACKING_FREQUENCY INTEGER,
LCS_QOS_REQ_TRACKING_PERIOD INTEGER,
LCS_QOS_REQ_VERTICAL_ACCUR INTEGER,
LDC_INFO_CARRIER_CODE INTEGER,
LDC_INFO_CONTRACT_PKEY VARCHAR2(30),
LDC_INFO_HOME_NET_IND INTEGER,
LEC_INFO_CONTRACT_PKEY VARCHAR2(30),
LEC_INFO_HOME_NET_IND INTEGER,
LZLIST VARCHAR2(40),
MC_INFO_CODE INTEGER,
MC_INFO_IND INTEGER,
MC_INFO_MICRO_CELL_INFORMATION INTEGER,
MC_SCALEFACTOR FLOAT,
MESSAGES_UMCODE INTEGER,
MESSAGES_VOLUME FLOAT,
MICRO_CELL_IMCSCALEFACTORTYPE VARCHAR2(1),
MICRO_CELL_MC_CODE INTEGER,
MICRO_CELL_MC_PKEY VARCHAR2(15),
MICRO_CELL_MC_TYPE VARCHAR2(1),
MICRO_CELL_SCALEFACTOR FLOAT,
NETWORK_INIT_CONTEXT_IND INTEGER,
NET_ELEMENT_HOME_BID_ID INTEGER,
NET_ELEMENT_NETWORK_CODE INTEGER,
NET_ELEMENT_NETW_ELEMENT_ID INTEGER,
NET_ELEMENT_USER_PROFILE_ID INTEGER,
NORMED_NET_ELEM_ADDRESS VARCHAR2(100),
NORMED_NET_ELEM_INT_ACC_CODE VARCHAR2(10),
NORMED_NET_ELEM_NUMBER_PLAN INTEGER,
NORMED_RTD_NUM_ADDRESS VARCHAR2(100),
NORMED_RTD_NUM_INT_ACC_CODE VARCHAR2(10),
NORMED_RTD_NUM_NUMBER_PLAN INTEGER,
NORMTRKGRP_IN_ADDRESS VARCHAR2(100),
NORMTRKGRP_IN_NUMBERINGPLAN INTEGER,
NORMTRKGRP_OUT_ADDRESS VARCHAR2(100),
NORMTRKGRP_OUT_NUMBERINGPLAN INTEGER,
NUMBER_OF_REJECTIONS INTEGER,
OFFER_OFFER_SEQNO INTEGER,
OFFER_OFFER_SNCODE INTEGER,
ORIGIN_FIELD_ID INTEGER,
ORIG_ENTRY_DATE_TIMESTAMP DATE,
ORIG_ENTRY_DATE_TIMEZONE_ID INTEGER,
ORIG_ENTRY_DATE_TIMEZONE_PKEY VARCHAR2(20),
ORIG_ENTRY_DATE_TIME_OFFSET INTEGER,
OR_FLAG INTEGER,
O_P_NORMED_NUM_ADDRESS VARCHAR2(100),
O_P_NORMED_NUM_INT_ACC_CODE VARCHAR2(10),
O_P_NORMED_NUM_NUMBER_PLAN INTEGER,
O_P_NUMBER_ADDRESS VARCHAR2(100),
O_P_NUMBER_BACKUP_ADDRESS VARCHAR2(100),
O_P_NUMBER_CARRIER_CODE INTEGER,
O_P_NUMBER_CLIR INTEGER,
O_P_NUMBER_NUMBERING_PLAN INTEGER,
O_P_NUMBER_OTHER_LOCATION VARCHAR2(50),
O_P_NUMBER_TYPE_OF_NUMBER INTEGER,
O_P_NUMBER_USER_PROFILE_ID INTEGER,
O_P_PUBID_ADDRESS VARCHAR2(100),
O_P_PUBID_NUMBERING_PLAN INTEGER,
O_P_PUBID_TYPE_OF_NUMBER INTEGER,
PRICE_PLAN_INFO_CHRGPLANID INTEGER,
PRICE_PLAN_INFO_EVALQUANTITY FLOAT,
PRICE_PLAN_INFO_THRESHOLD FLOAT,
PROGRAM_ID FLOAT,
PROGRAM_NAME VARCHAR2(30),
PROMO_INFO_B_NUMBER_CAT INTEGER,
QOS_NEGOT_DELAY INTEGER,
QOS_NEGOT_MEAN_THROUGHPUT INTEGER,
QOS_NEGOT_PEAK_THROUGHPUT INTEGER,
QOS_NEGOT_PRECEDENCE INTEGER,
QOS_NEGOT_RELIABILITY INTEGER,
QOS_PROFILE INTEGER,
QOS_REQ_DELAY INTEGER,
QOS_REQ_MEAN_THROUGHPUT INTEGER,
QOS_REQ_PEAK_THROUGHPUT INTEGER,
QOS_REQ_PRECEDENCE INTEGER,
QOS_REQ_RELIABILITY INTEGER,
RATED_CLICKS_UMCODE INTEGER,
RATED_CLICKS_VOLUME FLOAT,
RATED_FLAT_AMNT_GROSS_IND_NRPC INTEGER,
RATED_FLAT_AMNT_ORIG_CURRENCY INTEGER,
RATED_FLAT_AMNT_ORIG_GROSS_IND INTEGER,
RATED_FLAT_AMNT_TAX_NRPC FLOAT,
RATED_FLAT_AMOUNT FLOAT,
RATED_FLAT_AMOUNT_CURRENCY INTEGER,
RATED_FLAT_AMOUNT_GROSS_IND INTEGER,
RATED_FLAT_AMOUNT_NON_RPC FLOAT,
RATED_FLAT_AMOUNT_NON_RPC_CURR INTEGER,
RATED_FLAT_AMOUNT_ORIG_AMOUNT FLOAT,
RATED_FLAT_AMOUNT_ORIG_TAX FLOAT,
RATED_FLAT_AMOUNT_TAX FLOAT,
RATED_VOLUME FLOAT,
RATED_VOLUME_UMCODE INTEGER,
RECIPIENT_NET_ADDRESS VARCHAR2(100),
RECIPIENT_NET_NUMBERING_PLAN INTEGER,
RECORD_ID_CALL_ID INTEGER,
RECORD_ID_CDR_ID INTEGER,
RECORD_ID_CDR_SUB_ID INTEGER,
RECORD_ID_EVENT_REF VARCHAR2(60),
RECORD_ID_ORIG_CDR_ID INTEGER,
RECORD_ID_RAP_SEQUENCE_NUM INTEGER,
RECORD_ID_RERATE_SEQNO INTEGER,
RECORD_ID_SHAACC_UNIQUE_ID VARCHAR2(285),
RECORD_ID_TAP_SEQUENCE_NUM INTEGER,
RECORD_ID_UDR_FILE_ID INTEGER,
RECORD_TYPE_RECORD_CATEGORY INTEGER,
RECORD_TYPE_SUMMARY_IND INTEGER,
REFER_CONTR_CONTRACT_ID INTEGER,
REFER_CONTR_REFERENCE_TYPE INTEGER,
REJECTED_BASE_PART INTEGER,
REJECT_REASON_CODE VARCHAR2(5),
REMARK VARCHAR2(80),
RERATE_INFO_RERATE_REASON_ID INTEGER,
RERATE_INFO_RERATE_RECORD_TYPE VARCHAR2(1),
RERATE_INFO_RERATE_REQUEST_ID INTEGER,
RERATE_INFO_URH_ID INTEGER,
ROUNDED_VOLUME FLOAT,
ROUNDED_VOLUME_UMCODE INTEGER,
ROUTING_NETWORK_CODE INTEGER,
ROUTING_NUMBER_BACKUP_ADDRESS VARCHAR2(100),
ROUTING_USER_PROFILE_ID INTEGER,
SCU_ID_ADDRESS VARCHAR2(100),
SCU_ID_USER_PROFILE_ID INTEGER,
SCU_INFO_PRIORITY_CODE INTEGER,
SERVICE_ACTION_CODE VARCHAR2(1),
SERVICE_GUARANTEED_BIT_RATE INTEGER,
SERVICE_HSCSD_IND INTEGER,
SERVICE_IMS_SIGNALLING_CONTEXT INTEGER,
SERVICE_LOGIC_CODE VARCHAR2(50),
SERVICE_MAX_BIT_RATE INTEGER,
SERVICE_SERVICE_TYPE VARCHAR2(1),
SERVICE_USED_SERVICE INTEGER,
SERVICE_USER_PROTOCOL_IND INTEGER,
SERVICE_VAS_CODE VARCHAR2(10),
SERV_PDP_ADDR_APN_SPLIT_IND INTEGER,
SGSN_ADDRESSES VARCHAR2(65),
SPEC_NUM_INFO_APPLY_FREE_UNITS INTEGER,
START_TIME_CHARGE_OFFSET INTEGER,
START_TIME_CHARGE_TIMESTAMP DATE,
START_TIME_OFFSET INTEGER,
START_TIME_TIMESTAMP DATE,
SUM_REFERENCE_SINGLE_ID INTEGER,
S_PDP_ADDRESS VARCHAR2(100),
S_PDP_CARRIER_CODE INTEGER,
S_PDP_CLIR INTEGER,
S_PDP_INTERN_ACCESS_CODE VARCHAR2(10),
S_PDP_MODIFICATION_IND INTEGER,
S_PDP_NETWORK_CODE INTEGER,
S_PDP_NUMBERING_PLAN INTEGER,
S_PDP_TYPE_OF_NUMBER INTEGER,
S_PDP_USER_PROFILE_ID INTEGER,
S_P_EQUIPMENT_CLASS_MARK VARCHAR2(1),
S_P_EQUIPMENT_NUMBER VARCHAR2(20),
S_P_HOME_ID_DESCRIPTION VARCHAR2(30),
S_P_HOME_ID_HOME_BID_ID INTEGER,
S_P_HOME_ID_NAME VARCHAR2(24),
S_P_HOME_ID_NETWORK VARCHAR2(5),
S_P_HOME_LOC_ADDRESS VARCHAR2(100),
S_P_HOME_LOC_NUMBERING_PLAN INTEGER,
S_P_LOCATION_ADDRESS VARCHAR2(100),
S_P_LOCATION_NUMBERING_PLAN INTEGER,
S_P_LOC_SERVING_BID_ID INTEGER,
S_P_LOC_SERVING_LOCATION VARCHAR2(50),
S_P_NUMBER_ADDRESS VARCHAR2(100),
S_P_NUMBER_HOME_BID_ID INTEGER,
S_P_NUMBER_NETWORK_CODE INTEGER,
S_P_NUMBER_NUMBERING_PLAN INTEGER,
S_P_NUMBER_USER_PROFILE_ID INTEGER,
S_P_PORT_ADDRESS VARCHAR2(100),
S_P_PORT_NUMBERING_PLAN INTEGER,
S_P_PORT_USER_PROFILE_ID INTEGER,
TARIFF_DETAIL_CHGBL_QUANTITY INTEGER,
TARIFF_DETAIL_EXT_CHRG_UDMCODE INTEGER,
TARIFF_DETAIL_INTERCONNECT_IND VARCHAR2(1),
TARIFF_DETAIL_RATE_TYPE_ID INTEGER,
TARIFF_DETAIL_RTX_CHARGE_TYPE VARCHAR2(1),
TARIFF_DETAIL_TTCODE INTEGER,
TARIFF_INFO_CATALOGUE_ID INTEGER,
TARIFF_INFO_CATALOGUE_VERS INTEGER,
TARIFF_INFO_CTLG_ELM_ID INTEGER,
TARIFF_INFO_EGCODE INTEGER,
TARIFF_INFO_EGVERSION INTEGER,
TARIFF_INFO_GVCODE INTEGER,
TARIFF_INFO_PRICELIST_ID INTEGER,
TARIFF_INFO_PRICELIST_PKEY VARCHAR2(16),
TARIFF_INFO_PRICELIST_VERS INTEGER,
TARIFF_INFO_PRICE_DEF_VERS INTEGER,
TARIFF_INFO_RPCODE INTEGER,
TARIFF_INFO_RPVERSION INTEGER,
TARIFF_INFO_SNCODE INTEGER,
TARIFF_INFO_SPCODE INTEGER,
TARIFF_INFO_TIME_BAND_CODE VARCHAR2(2),
TARIFF_INFO_TMCODE INTEGER,
TARIFF_INFO_TMVERSION INTEGER,
TARIFF_INFO_TM_USED_TYPE INTEGER,
TARIFF_INFO_TWCODE INTEGER,
TARIFF_INFO_USAGE_IND INTEGER,
TARIFF_INFO_ZNCODE INTEGER,
TARIFF_INFO_ZPCODE INTEGER,
TARIFF_INFO_ZPCODE_DAY_CATCODE VARCHAR2(2),
TAX_INFO_SERV_CAT VARCHAR2(10),
TAX_INFO_SERV_CODE VARCHAR2(10),
TAX_INFO_SERV_TYPE VARCHAR2(3),
TECHN_INFO_FIXED_MOBILE_IND VARCHAR2(1),
TECHN_INFO_HOME_TERMINATED_IND VARCHAR2(1),
TECHN_INFO_PREPAY_IND VARCHAR2(1),
TECHN_INFO_PRE_RATED_IND INTEGER,
TECHN_INFO_REV_CHARGING_IND INTEGER,
TECHN_INFO_SCCODE INTEGER,
TECHN_INFO_TERMINATION_IND INTEGER,
TRUNK_GROUP_IN_ADDRESS VARCHAR2(100),
TRUNK_GROUP_IN_NUMBERINGPLAN INTEGER,
TRUNK_GROUP_IN_TYPEOFNUMBER INTEGER,
TRUNK_GROUP_OUT_ADDRESS VARCHAR2(100),
TRUNK_GROUP_OUT_NUMBERINGPLAN INTEGER,
TRUNK_GROUP_OUT_TYPEOFNUMBER INTEGER,
T_P_NUMBER_USER_PROFILE_ID INTEGER,
UDR_BASEPART_ID INTEGER,
UDR_CHARGEPART_ID INTEGER,
UDS_BASE_PART_ID INTEGER,
UDS_CHARGE_PART_ID INTEGER,
UDS_FREE_UNIT_PART_ID INTEGER,
UDS_PROMOTION_PART_ID INTEGER,
UDS_RECORD_ID INTEGER,
UDS_STREAM_ID INTEGER,
UMTS_QOS_NEGOT_ALLC_RETN_PRIOR INTEGER,
UMTS_QOS_NEGOT_DELAY INTEGER,
UMTS_QOS_NEGOT_DELIVERY_ORDER INTEGER,
UMTS_QOS_NEGOT_ERRONEOUS_SDUS INTEGER,
UMTS_QOS_NEGOT_HANDL_PRIORITY INTEGER,
UMTS_QOS_NEGOT_MAX_SIZE_SDU INTEGER,
UMTS_QOS_NEGOT_RATE_DOWNLINK INTEGER,
UMTS_QOS_NEGOT_RATE_UPLINK INTEGER,
UMTS_QOS_NEGOT_RESIDUAL_BER INTEGER,
UMTS_QOS_NEGOT_SDU_ERR_RATIO INTEGER,
UMTS_QOS_NEGOT_TRAFFIC_CLASS INTEGER,
UMTS_QOS_REQ_ALLC_RETN_PRIOR INTEGER,
UMTS_QOS_REQ_DELAY INTEGER,
UMTS_QOS_REQ_DELIVERY_ORDER INTEGER,
UMTS_QOS_REQ_ERRONEOUS_SDUS INTEGER,
UMTS_QOS_REQ_HANDL_PRIORITY INTEGER,
UMTS_QOS_REQ_MAX_SIZE_SDU INTEGER,
UMTS_QOS_REQ_RATE_DOWNLINK INTEGER,
UMTS_QOS_REQ_RATE_UPLINK INTEGER,
UMTS_QOS_REQ_RESIDUAL_BER INTEGER,
UMTS_QOS_REQ_SDU_ERROR_RATIO INTEGER,
UMTS_QOS_REQ_TRAFFIC_CLASS INTEGER,
UNBILLEDAMTPAYMRESP_CUSTOMERID INTEGER,
UNBILLED_AMOUNT_AMOUNT FLOAT,
UNBILLED_AMOUNT_CURRENCY INTEGER,
UNBILLED_AMOUNT_GROSS_IND INTEGER,
UNBILLED_AMOUNT_TAX FLOAT,
UPLINK_VOLUME_UMCODE INTEGER,
UPLINK_VOLUME_VOLUME FLOAT,
VPN_INFO_VPN_CALL_TYPE INTEGER,
VPN_NUMBER_ADDRESS VARCHAR2(100),
VPN_NUMBER_CARRIER_CODE INTEGER,
VPN_NUMBER_CLIR INTEGER,
VPN_NUMBER_DYNAMIC_ADDRESS INTEGER,
VPN_NUMBER_INT_ACCESS_CODE VARCHAR2(10),
VPN_NUMBER_LOCAL_PREFIX_LEN INTEGER,
VPN_NUMBER_MODIFICATION_IND INTEGER,
VPN_NUMBER_NETWORK_CODE INTEGER,
VPN_NUMBER_NUMBERING_PLAN INTEGER,
VPN_NUMBER_TYPE_OF_NUMBER INTEGER,
VPN_NUMBER_USER_PROFILE_ID INTEGER,
XFILE_BASE_CHARGE_AMOUNT FLOAT,
XFILE_BASE_CHARGE_CURRENCY INTEGER,
XFILE_BASE_CHARGE_GROSS_IND INTEGER,
XFILE_BASE_CHARGE_TAX FLOAT,
XFILE_CALL_TYPE VARCHAR2(2),
XFILE_CHARGE_AMOUNT FLOAT,
XFILE_CHARGE_CURRENCY INTEGER,
XFILE_CHARGE_GROSS_IND INTEGER,
XFILE_CHARGE_TAX FLOAT,
XFILE_DAY_CATEGORY_CODE VARCHAR2(2),
XFILE_DISCOUNT_AMOUNT FLOAT,
XFILE_DISCOUNT_CURRENCY INTEGER,
XFILE_IC_CHARGE_AMOUNT FLOAT,
XFILE_IC_CHARGE_CURRENCY INTEGER,
XFILE_IC_CHARGE_GROSS_IND INTEGER,
XFILE_IC_CHARGE_TAX FLOAT,
XFILE_IND VARCHAR2(1),
XFILE_TIME_BAND_CODE VARCHAR2(2),
ZERO_RATED_VOLUME_UMCODE INTEGER,
ZERO_RATED_VOLUME_VOLUME FLOAT,
ZERO_ROUNDED_VOLUME_UMCODE INTEGER,
ZERO_ROUNDED_VOLUME_VOLUME FLOAT,
BAL_AUDIT_DAT_VALID_FROM DATE,
BAL_AUDIT_DAT_VALID_TO DATE,
CHRGAGGRINFO_REQUEST_ID INTEGER,
CUST_INFO_CUSTOMER_GROUP VARCHAR2(10),
CUST_INFO_PARENT_CONTRACT_ID INTEGER,
IMP_PARTY1_PARENT_CONTRACT_ID INTEGER,
IMP_PARTY2_PARENT_CONTRACT_ID INTEGER,
IMP_PARTY3_PARENT_CONTRACT_ID INTEGER,
NET_ELEMENT_ADDRESS VARCHAR2(100),
NET_ELEMENT_NUMBERING_PLAN INTEGER,
NET_ELEMENT_TYPE_OF_NUMBER INTEGER,
RATED_FLAT_AMNT_ORIG_DISC_AMNT FLOAT,
RATED_FLAT_AMOUNT_DISC_AMOUNT FLOAT,
ROUTING_ADDRESS VARCHAR2(100),
ROUTING_NUMBERING_PLAN INTEGER,
ROUTING_TYPE_OF_NUMBER INTEGER,
TARIFF_DETAIL_PRICGALTERNPKEY VARCHAR2(5),
TARIFF_DETAIL_PRICINGALTERNID INTEGER,
T_P_NUMBER_ADDRESS VARCHAR2(100),
T_P_NUMBER_NUMBERING_PLAN INTEGER,
T_P_NUMBER_TYPE_OF_NUMBER INTEGER,
UNBILLED_AMOUNT_BILLING_ACC FLOAT,
UNBILLED_AMOUNT_COMPL_COND_ID INTEGER
,CONSTRAINT PK_UDR_ST_CRLP
PRIMARY KEY
(
CUST_INFO_CUSTOMER_ID,
CUST_INFO_CONTRACT_ID,
CUST_INFO_BILL_CYCLE,
UDS_STREAM_ID,
UDS_RECORD_ID,
UDS_BASE_PART_ID,
UDS_CHARGE_PART_ID,
UDS_FREE_UNIT_PART_ID,
ENTRY_DATE_TIMESTAMP
) USING INDEX
)
PARTITION BY RANGE (
ENTRY_DATE_TIMESTAMP
)
(
PARTITION PART_201606 VALUES LESS THAN ( TO_DATE('01.07.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201607 VALUES LESS THAN ( TO_DATE('01.08.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201608 VALUES LESS THAN ( TO_DATE('01.09.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201609 VALUES LESS THAN ( TO_DATE('01.10.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201610 VALUES LESS THAN ( TO_DATE('01.11.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201611 VALUES LESS THAN ( TO_DATE('01.12.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201612 VALUES LESS THAN ( TO_DATE('01.01.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201701 VALUES LESS THAN ( TO_DATE('01.02.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201702 VALUES LESS THAN ( TO_DATE('01.03.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201703 VALUES LESS THAN ( TO_DATE('01.04.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201704 VALUES LESS THAN ( TO_DATE('01.05.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201705 VALUES LESS THAN ( TO_DATE('01.06.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201706 VALUES LESS THAN ( TO_DATE('01.07.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201707 VALUES LESS THAN ( TO_DATE('01.08.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201708 VALUES LESS THAN ( TO_DATE('01.09.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201709 VALUES LESS THAN ( TO_DATE('01.10.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201710 VALUES LESS THAN ( TO_DATE('01.11.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201711 VALUES LESS THAN ( TO_DATE('01.12.2017 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201712 VALUES LESS THAN ( TO_DATE('01.01.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201801 VALUES LESS THAN ( TO_DATE('01.02.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201802 VALUES LESS THAN ( TO_DATE('01.03.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201803 VALUES LESS THAN ( TO_DATE('01.04.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201804 VALUES LESS THAN ( TO_DATE('01.05.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201805 VALUES LESS THAN ( TO_DATE('01.06.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201806 VALUES LESS THAN ( TO_DATE('01.07.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201807 VALUES LESS THAN ( TO_DATE('01.08.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201808 VALUES LESS THAN ( TO_DATE('01.09.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201809 VALUES LESS THAN ( TO_DATE('01.10.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201810 VALUES LESS THAN ( TO_DATE('01.11.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201811 VALUES LESS THAN ( TO_DATE('01.12.2018 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201812 VALUES LESS THAN ( TO_DATE('01.01.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201901 VALUES LESS THAN ( TO_DATE('01.02.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201902 VALUES LESS THAN ( TO_DATE('01.03.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201903 VALUES LESS THAN ( TO_DATE('01.04.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201904 VALUES LESS THAN ( TO_DATE('01.05.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201905 VALUES LESS THAN ( TO_DATE('01.06.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201906 VALUES LESS THAN ( TO_DATE('01.07.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201907 VALUES LESS THAN ( TO_DATE('01.08.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201908 VALUES LESS THAN ( TO_DATE('01.09.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201909 VALUES LESS THAN ( TO_DATE('01.10.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201910 VALUES LESS THAN ( TO_DATE('01.11.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201911 VALUES LESS THAN ( TO_DATE('01.12.2019 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_201912 VALUES LESS THAN ( TO_DATE('01.01.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202001 VALUES LESS THAN ( TO_DATE('01.02.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202002 VALUES LESS THAN ( TO_DATE('01.03.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202003 VALUES LESS THAN ( TO_DATE('01.04.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202004 VALUES LESS THAN ( TO_DATE('01.05.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202005 VALUES LESS THAN ( TO_DATE('01.06.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202006 VALUES LESS THAN ( TO_DATE('01.07.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202007 VALUES LESS THAN ( TO_DATE('01.08.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202008 VALUES LESS THAN ( TO_DATE('01.09.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202009 VALUES LESS THAN ( TO_DATE('01.10.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202010 VALUES LESS THAN ( TO_DATE('01.11.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202011 VALUES LESS THAN ( TO_DATE('01.12.2020 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202012 VALUES LESS THAN ( TO_DATE('01.01.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202101 VALUES LESS THAN ( TO_DATE('01.02.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202102 VALUES LESS THAN ( TO_DATE('01.03.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202103 VALUES LESS THAN ( TO_DATE('01.04.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202104 VALUES LESS THAN ( TO_DATE('01.05.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202105 VALUES LESS THAN ( TO_DATE('01.06.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202106 VALUES LESS THAN ( TO_DATE('01.07.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202107 VALUES LESS THAN ( TO_DATE('01.08.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202108 VALUES LESS THAN ( TO_DATE('01.09.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202109 VALUES LESS THAN ( TO_DATE('01.10.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202110 VALUES LESS THAN ( TO_DATE('01.11.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202111 VALUES LESS THAN ( TO_DATE('01.12.2021 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202112 VALUES LESS THAN ( TO_DATE('01.01.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202201 VALUES LESS THAN ( TO_DATE('01.02.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202202 VALUES LESS THAN ( TO_DATE('01.03.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202203 VALUES LESS THAN ( TO_DATE('01.04.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202204 VALUES LESS THAN ( TO_DATE('01.05.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202205 VALUES LESS THAN ( TO_DATE('01.06.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202206 VALUES LESS THAN ( TO_DATE('01.07.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202207 VALUES LESS THAN ( TO_DATE('01.08.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202208 VALUES LESS THAN ( TO_DATE('01.09.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202209 VALUES LESS THAN ( TO_DATE('01.10.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202210 VALUES LESS THAN ( TO_DATE('01.11.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202211 VALUES LESS THAN ( TO_DATE('01.12.2022 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202212 VALUES LESS THAN ( TO_DATE('01.01.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202301 VALUES LESS THAN ( TO_DATE('01.02.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202302 VALUES LESS THAN ( TO_DATE('01.03.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202303 VALUES LESS THAN ( TO_DATE('01.04.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202304 VALUES LESS THAN ( TO_DATE('01.05.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202305 VALUES LESS THAN ( TO_DATE('01.06.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202306 VALUES LESS THAN ( TO_DATE('01.07.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202307 VALUES LESS THAN ( TO_DATE('01.08.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202308 VALUES LESS THAN ( TO_DATE('01.09.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202309 VALUES LESS THAN ( TO_DATE('01.10.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202310 VALUES LESS THAN ( TO_DATE('01.11.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202311 VALUES LESS THAN ( TO_DATE('01.12.2023 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202312 VALUES LESS THAN ( TO_DATE('01.01.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202401 VALUES LESS THAN ( TO_DATE('01.02.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202402 VALUES LESS THAN ( TO_DATE('01.03.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202403 VALUES LESS THAN ( TO_DATE('01.04.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202404 VALUES LESS THAN ( TO_DATE('01.05.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202405 VALUES LESS THAN ( TO_DATE('01.06.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202406 VALUES LESS THAN ( TO_DATE('01.07.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202407 VALUES LESS THAN ( TO_DATE('01.08.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202408 VALUES LESS THAN ( TO_DATE('01.09.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202409 VALUES LESS THAN ( TO_DATE('01.10.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202410 VALUES LESS THAN ( TO_DATE('01.11.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202411 VALUES LESS THAN ( TO_DATE('01.12.2024 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202412 VALUES LESS THAN ( TO_DATE('01.01.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202501 VALUES LESS THAN ( TO_DATE('01.02.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202502 VALUES LESS THAN ( TO_DATE('01.03.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202503 VALUES LESS THAN ( TO_DATE('01.04.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202504 VALUES LESS THAN ( TO_DATE('01.05.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202505 VALUES LESS THAN ( TO_DATE('01.06.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202506 VALUES LESS THAN ( TO_DATE('01.07.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202507 VALUES LESS THAN ( TO_DATE('01.08.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202508 VALUES LESS THAN ( TO_DATE('01.09.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202509 VALUES LESS THAN ( TO_DATE('01.10.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202510 VALUES LESS THAN ( TO_DATE('01.11.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202511 VALUES LESS THAN ( TO_DATE('01.12.2025 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202512 VALUES LESS THAN ( TO_DATE('01.01.2026 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202601 VALUES LESS THAN ( TO_DATE('01.02.2026 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202602 VALUES LESS THAN ( TO_DATE('01.03.2026 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202603 VALUES LESS THAN ( TO_DATE('01.04.2026 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202604 VALUES LESS THAN ( TO_DATE('01.05.2026 00:00:00','DD.MM.YYYY HH24:MI:SS')
)  ,
PARTITION PART_202605 VALUES LESS THAN ( TO_DATE('01.06.2026 00:00:00','DD.MM.YYYY HH24:MI:SS')
)
)
/
ALTER TABLE UDR_ST_CRLP
MODIFY
(
CUST_INFO_BILL_CYCLE NOT NULL
)
/
COMMENT ON TABLE UDR_ST_CRLP IS 'Table for Rated Subscriber Short Term Record (RLH)'
/
COMMENT ON COLUMN UDR_ST_CRLP.AGGREG_INFO_AGGREG_PURPOSE IS 'Aggregation information - Aggregation purpose'
/
COMMENT ON COLUMN UDR_ST_CRLP.AGGREG_INFO_AGG_TRANS_ID IS 'Aggregation information - Aggregation transaction identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.AGGREG_INFO_APPLIED_PACK_ID IS 'Aggregation information - Applied aggregation package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.AGGREG_INFO_REC_COUNTER IS 'Aggregation information - Total no. of records'
/
COMMENT ON COLUMN UDR_ST_CRLP.AGGREG_INFO_SUMMARY_ID IS 'Aggregation information - Summary record identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.ALT_RATED_AMOUNT IS 'Alternate rated charge - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.ALT_RATED_CURRENCY IS 'Alternate rated charge - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.ALT_TARIFF_CLICKS_VOLUME IS 'Alternate rated clicks - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.ALT_TMCODE IS 'Alternate rate plan - Rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.AN_PACK_AN_PACKAGE_ID_LIST IS 'Anonymization package identifier - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.AN_PACK_ORIG_AN_PACK_ID_LIST IS 'Anonymization package backup identifier - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DATA_ACCOUNT_ID IS 'Balance audit data - Account identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DATA_ACCOUNT_TYPE IS 'Balance audit data - Type of account that is impacted:'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DATA_ACCOUNT_TYPE_ID IS 'Balance audit data - Account type identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_BALANCE_ACCUM IS 'Balance audit data - Balance accumulated for the charge part'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_BALANCE_PROD_ID IS 'Balance audit data - Service code of the cost control service'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_BALANCE_TYPE IS 'Balance audit data - Balance type'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_BAL_AFTER_CHG IS 'Balance audit data - Balance after charge'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_BAL_BEFORE_CHG IS 'Balance audit data - Balance before charge'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_BUNDL_PROD_ID IS 'Balance audit data - Bundled product identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_CONTRACT_ID IS 'Balance audit data - Contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_OFFER_SEQNO IS 'Balance audit data - Offer sequence no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_OFFER_SNCODE IS 'Balance audit data - Offer service name code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_PREP_CREDIT_IND IS 'Balance audit data - Prepaid credit indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_PURCHASE_SEQ_NO IS 'Balance audit data - Purchase seq no / Balance seq no'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_SHACC_PACKID IS 'Balance audit data - Shared account package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_USER_PROFILE_ID IS 'Balance audit data - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_BOP_PACKAGE_ID IS 'BOP information - BOP package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_BOP_PACKAGE_PKEY IS 'BOP information - BOP package public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_BOP_PACKAGE_VERSION IS 'BOP information - BOP package version'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_DETAIL_BILLED_IND IS 'BOP information detail - Billed indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_DETAIL_BOP_ALTERN_IND IS 'BOP information detail - BOP alternative indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_DETAIL_CONTRACTED_IND IS 'BOP information detail - Contracted alternative indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_DETAIL_SEQUENCE_RP IS 'BOP information detail - BOP entry (Service Package) seq. number'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_INFO_DETAIL_SEQUENCE_SP IS 'BOP information detail - BOP entry (Rating Package) seq. number'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_DAY_CATCODE IS 'BOP tariff information - Day category code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_EGCODE IS 'BOP tariff information - Extended GL code package code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_EGVERSION IS 'BOP tariff information - Extended GL code package version'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_GVCODE IS 'BOP tariff information - Zone coverage code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_RPCODE IS 'BOP tariff information - Rating package code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_RPVERSION IS 'BOP tariff information - Rating package version'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_SNCODE IS 'BOP tariff information - Service name code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_SPCODE IS 'BOP tariff information - Service package code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_TIME_BAND_CODE IS 'BOP tariff information - Time band code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_TMCODE IS 'BOP tariff information - Rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_TMVERSION IS 'BOP tariff information - Rate plan version'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_TM_USED_TYPE IS 'BOP tariff information - Type of rate plan used for rating'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_TWCODE IS 'BOP tariff information - Tariff week code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_USAGE_IND IS 'BOP tariff information - Usage indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_ZNCODE IS 'BOP tariff information - Tariff zone code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BOP_TARIFF_INFO_ZPCODE IS 'BOP tariff information - Terminating zonal point code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BPARTN_SUM_INFO_TIME_SLICE_LB IS 'Summary record information - Time slice left boundary in seconds'
/
COMMENT ON COLUMN UDR_ST_CRLP.BPARTN_SUM_INFO_TIME_SLICE_RB IS 'Summary record information - Time slice right boundary in seconds'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_BUNDLE_PURCHASE_ID IS 'Bundle information - Bundle purchase identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_BUNDLE_PURCH_IND IS 'Bundle information - Bundle purchase indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_CONTRACT_ID IS 'Bundle information - Contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_PURCHASE_SEQ_NO IS 'Bundle information - Purchase seq no / Balance seq no'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_SEQUENCE_NUMBER IS 'Bundle information - Increased number identifing the snapshot'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_SNCODE IS 'Bundle information - Service name code'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_STATE IS 'Bundle information - Purchased bundle sate'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_TERMINATION IS 'Bundle information - Termination date'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_USER_PROFILE_ID IS 'Bundle information - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_VALID_FROM IS 'Bundle information - Start date'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_VALID_TO IS 'Bundle information - End date'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_INFO_VERSION IS 'Bundle information - Version number'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUNDLE_USG_BUNDLE_COVERED_USG IS 'Bundle usage - Usage covered by bundle'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_BS_ID IS 'Pre- and business scenario information - Business scenario identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_BS_VERSION IS 'Pre- and business scenario information - Business scenario version'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_CHARGE_ITEM_ID IS 'Pre- and business scenario information - Charge party item identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_CHARGE_PARTY_ID IS 'Pre- and business scenario information - Charge party entry identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_C_P_FIELD_REF IS 'Pre- and business scenario information - Reference field of the charged party'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_O_P_FIELD_REF IS 'Pre- and business scenario information - Reference field of the other party'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_PRE_BS_ID IS 'Pre- and business scenario information - Pre-business scenario identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUSINESS_INFO_PRE_BS_VERSION IS 'Pre- and business scenario information - Pre-business scenario version'
/
COMMENT ON COLUMN UDR_ST_CRLP.BUS_PARTNER_INFO_TAX_MODE IS 'Details about business partner - Tax mode indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CALL_DEST IS 'Call destination - Destination of a MOC originated in HPLMN'
/
COMMENT ON COLUMN UDR_ST_CRLP.CALL_TYPE IS 'Call type information - Call type for call scenario'
/
COMMENT ON COLUMN UDR_ST_CRLP.CAMEL_DEST_ADDR_USER_PROF_ID IS 'CAMEL call destination - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CAMEL_MSC_ADDRESS IS 'CAMEL service center address - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.CAMEL_MSC_ADDR_USER_PROF_ID IS 'CAMEL service center address - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CAMEL_REFERENCE_NUMBER IS 'CAMEL details - CAMEL reference no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.CAMEL_SRV_ADDR_USER_PROF_ID IS 'CAMEL server address - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CHARGE_INFO_CASH_FLOW_DIRECT IS 'Charge information - Cash flow direction'
/
COMMENT ON COLUMN UDR_ST_CRLP.CHARGE_INFO_DISABLE_TAX IS 'Charge information - Disable tax calculation'
/
COMMENT ON COLUMN UDR_ST_CRLP.CHARGING_CHARACTERISTICS IS 'Basic call type of record - Charging characteristics'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONSUMER_INFO_ADDRESS IS 'Consumer info - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONSUMER_INFO_CONTRACT_ID IS 'Consumer info - Contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONSUMER_INFO_NUMBERING_PLAN IS 'Consumer info - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_ADVISED_CHARGE_IND IS 'Content Service Used Information - Advised charge indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_AUTHORISATION_CODE IS 'Content Service Used Information - Transaction authorization code'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_CONTENT_CHARGING_POINT IS 'Content Service Used Information - Content charging point'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_CONTRACT_PKEY IS 'Content Service Used Information - Contract public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_DESC_SUPPRESS IS 'Content Service Used Information - Transaction description suppression'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PAID_IND IS 'Content Service Used Information - Paid indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PAYMENT_METHOD IS 'Content Service Used Information - Payment method'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVIDER_ADDRESS IS 'Content provider - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVIDER_CARRIER_CODE IS 'Content provider - Carrier code'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVIDER_CLIR IS 'Content provider - Calling line identifier restriction'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVIDER_IAC IS 'Content provider - International access code'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVIDER_MODIF_IND IS 'Content provider - Modification indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVIDER_NETWORK_CODE IS 'Content provider - Hosting network code'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVID_DYNAMIC_ADDRESS IS 'Content provider - Dynamic address indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVID_LOCAL_PREF_LEN IS 'Content provider - Length of the local prefix'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVID_NUMBERING_PLAN IS 'Content provider - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVID_OTHER_LOCATION IS 'Content provider - Other location'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVID_TYPE_OF_NUMBER IS 'Content provider - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_PROVID_USER_PROFILE_ID IS 'Content provider - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_REFUND_IND IS 'Content Service Used Information - Charge refund indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_SHORT_DESC IS 'Content Service Used Information - Content catalog element external key'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTENT_TRANSACTION_ID IS 'Content Service Used Information - Transaction identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CONTROL_DATA_RECORD_AGE IS 'Control data used by prepaid - Age of the record in seconds'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUG_INFO_CUG_ID IS 'CUG information - CUG identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUG_INFO_CUG_INDEX IS 'CUG information - CUG index (subscription specific)'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUSTOMER_INFO_CONTRACT_TYPE_ID IS 'Customer information of charged party - Contract type identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUSTOMER_INFO_CONTRAGGRPACK_ID IS 'Customer information of charged party - Contracted aggreg. package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUSTOMER_INFO_RECO_IND IS 'Customer information of charged party - Reconciliation contract indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_ADDRESS IS 'Customer information of charged party - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_ALTERNATE_TMCODE IS 'Customer information of charged party - Alternate rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_AN_PACKAGE_ID_LIST IS 'Customer information of charged party - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_BILL_CYCLE IS 'Customer information of charged party - Billing cycle'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_BU_ADDRESS IS 'Customer information of charged party - Business unit address'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_BU_NUMBERING_PLAN IS 'Customer information of charged party - Numbering plan code for business unit'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_CHARGING_ENGINE IS 'Customer information of charged party - Used Charging Engine'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_CONTRACT_ID IS 'Customer information of charged party - Contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_CUSTOMER_ID IS 'Customer information of charged party - Customer identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_DELETE_AFTER_BILLING IS 'Customer information of charged party - Delete after billing indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_DN_ID IS 'Customer information of charged party - Directory number identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_MAIN_MSISDN IS 'Customer information of charged party - Main directory number of contract'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_NUMBERING_PLAN IS 'Customer information of charged party - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_PORT_ID IS 'Customer information of charged party - Port identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_SERV_BID_ID IS 'Customer information of charged party - Serving BID ID'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_SIM_NUMBER IS 'Customer information of charged party - SIM number'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_SIM_SERNUMBER IS 'Customer information of charged party - SIM serial number'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_SUBS_CODE IS 'Customer information of charged party - Contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_SUBS_TAG IS 'Customer information of charged party - Party type indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_USER_PROFILE_ID IS 'Customer information of charged party - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.DATA_VOLUME IS 'Call data volume - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.DATA_VOLUME_UMCODE IS 'Call data volume - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.DESC_PROD_USAGE_LONG_DESC IS 'Description type - Product usage description'
/
COMMENT ON COLUMN UDR_ST_CRLP.DESTINATION_FIELD_ID IS 'UDR field used as destination - UDR field identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.DOWNLINK_VOLUME_UMCODE IS 'Downlink data volume - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.DOWNLINK_VOLUME_VOLUME IS 'Downlink data volume - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.DURATION_UMCODE IS 'Call duration - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.DURATION_VOLUME IS 'Call duration - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.ENTRY_DATE_OFFSET IS 'Record entry date - Time offset'
/
COMMENT ON COLUMN UDR_ST_CRLP.ENTRY_DATE_TIMESTAMP IS 'Record entry date - UTC timestamp'
/
COMMENT ON COLUMN UDR_ST_CRLP.EVENT_INFO_EVENT_TYPE IS 'Event information - Event information'
/
COMMENT ON COLUMN UDR_ST_CRLP.EVENT_STATUS_INFO_MESSAGE_ID IS 'Event status information - Event message identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.EVENT_UMCODE IS 'Call events - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.EVENT_VOLUME IS 'Call events - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.EXPORT_FILE IS 'Export file information - Export file name'
/
COMMENT ON COLUMN UDR_ST_CRLP.EXT_BALANCE_AMNT_AMOUNT IS 'Balance amount as determined by CS - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOLLOW_UP_CALL_TYPE IS 'Call type information - Internal business scenario call type'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_AMOUNT_AMOUNT IS 'Amount in foreign currency - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_AMOUNT_CURRENCY IS 'Amount in foreign currency - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_AMOUNT_GROSS_IND IS 'Amount in foreign currency - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_AMOUNT_TAX IS 'Amount in foreign currency - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_FREECHRG_AMOUNT IS 'Discount in foreign currency - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_FREECHRG_CURRENCY IS 'Discount in foreign currency - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_FREECHRG_GROSS_IND IS 'Discount in foreign currency - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.FOR_FREECHRG_TAX IS 'Discount in foreign currency - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_AMOUNT IS 'Free charge granted - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_AMOUNT_NON_RPC IS 'Contains free charges in home currency - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_CURRENCY IS 'Free charge granted - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_CURR_NON_RPC IS 'Contains free charges in home currency - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_GROSS_IND IS 'Free charge granted - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_GROSS_IND_NRPC IS 'Contains free charges in home currency - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_TAX IS 'Free charge granted - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CHARGE_TAX_NRPC IS 'Contains free charges in home currency - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CLICKS_UMCODE IS 'Free clicks granted - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_CLICKS_VOLUME IS 'Free clicks granted - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_RATED_VOLUME_UMCODE IS 'Rated volume of free units - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_RATED_VOLUME_VOLUME IS 'Rated volume of free units - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_ROUNDED_VOLUME_UMCODE IS 'Rounded volume of free units - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_ROUNDED_VOLUME_VOLUME IS 'Rounded volume of free units - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_ACCOUNT_KEY IS 'Free units information - Free unit account key'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_ACCOUNT_ORIGIN IS 'Free units information - Origin of the free unit part'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_ACC_HIST_ID IS 'Free units information - Free unit account history identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_APPL_METHOD IS 'Free units information - Application method'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_CHG_RED_QUOTA IS 'Free units information - Charge reduction quota'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_DISCOUNT_RATE IS 'Free units information - Discount rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_DISCOUNT_TYPE IS 'Free units information - Discount type'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_FREEUNITOPTION IS 'Free units information - Free unit option'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_FUP_SEQ IS 'Free units information - Free unit package sequences'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_FU_PACK_ID IS 'Free units information - Free unit package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_PART_CREATOR IS 'Free units information - Producer of the free unit part'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_PREVIOUS_SEQNO IS 'Free units information - Free unit part previous sequence no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_SEQNO IS 'Free units information - Free unit part sequence no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.FREE_UNITS_INFO_VERSION IS 'Free units information - Version number'
/
COMMENT ON COLUMN UDR_ST_CRLP.HOME_NETWORK_CODE IS 'Home network information - Hosting network code'
/
COMMENT ON COLUMN UDR_ST_CRLP.HSCSD_INFO_AIUR IS 'HSCSD information - Air interface user rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.HSCSD_INFO_CHANNELS_MAX IS 'HSCSD information - Maximum no. of channels'
/
COMMENT ON COLUMN UDR_ST_CRLP.HSCSD_INFO_CHANNELS_USED IS 'HSCSD information - No. of channels used'
/
COMMENT ON COLUMN UDR_ST_CRLP.HSCSD_INFO_CODING_ACC IS 'HSCSD information - Channel coding acceptable'
/
COMMENT ON COLUMN UDR_ST_CRLP.HSCSD_INFO_CODING_USED IS 'HSCSD information - Channel coding used'
/
COMMENT ON COLUMN UDR_ST_CRLP.HSCSD_INFO_FNUR IS 'HSCSD information - Fixed network user rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.HSCSD_INFO_INIT_PARTY IS 'HSCSD information - Initiating party'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY1_ADDRESS IS 'Customer information of impacted party 1 - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY1_ALTERNATE_TMCODE IS 'Customer information of impacted party 1 - Alternate rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY1_AN_PACKAGE_ID_LIST IS 'Customer information of impacted party 1 - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY1_BILL_CYCLE IS 'Customer information of impacted party 1 - Billing cycle'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY1_NUMBERING_PLAN IS 'Customer information of impacted party 1 - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY1_USER_PROFILE_ID IS 'Customer information of impacted party 1 - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY2_ADDRESS IS 'Customer information of impacted party 2 - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY2_ALTERNATE_TMCODE IS 'Customer information of impacted party 2 - Alternate rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY2_AN_PACKAGE_ID_LIST IS 'Customer information of impacted party 2 - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY2_BILL_CYCLE IS 'Customer information of impacted party 2 - Billing cycle'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY2_NUMBERING_PLAN IS 'Customer information of impacted party 2 - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY2_USER_PROFILE_ID IS 'Customer information of impacted party 2 - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY3_ADDRESS IS 'Customer information of impacted party 3 - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY3_ALTERNATE_TMCODE IS 'Customer information of impacted party 3 - Alternate rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY3_AN_PACKAGE_ID_LIST IS 'Customer information of impacted party 3 - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY3_BILL_CYCLE IS 'Customer information of impacted party 3 - Billing cycle'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY3_NUMBERING_PLAN IS 'Customer information of impacted party 3 - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY3_USER_PROFILE_ID IS 'Customer information of impacted party 3 - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY4_ADDRESS IS 'Customer information of impacted party 4 - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY4_ALTERNATE_TMCODE IS 'Customer information of impacted party 4 - Alternate rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY4_AN_PACKAGE_ID_LIST IS 'Customer information of impacted party 4 - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY4_BILL_CYCLE IS 'Customer information of impacted party 4 - Billing cycle'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY4_NUMBERING_PLAN IS 'Customer information of impacted party 4 - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY4_PARENT_CONTRACT_ID IS 'Customer information of impacted party 4 - Parent contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY4_USER_PROFILE_ID IS 'Customer information of impacted party 4 - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY5_ADDRESS IS 'Customer information of impacted party 5 - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY5_ALTERNATE_TMCODE IS 'Customer information of impacted party 5 - Alternate rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY5_AN_PACKAGE_ID_LIST IS 'Customer information of impacted party 5 - Anonymization package identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY5_BILL_CYCLE IS 'Customer information of impacted party 5 - Billing cycle'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY5_NUMBERING_PLAN IS 'Customer information of impacted party 5 - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY5_PARENT_CONTRACT_ID IS 'Customer information of impacted party 5 - Parent contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY5_USER_PROFILE_ID IS 'Customer information of impacted party 5 - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.INITIAL_START_TIME_TIMESTAMP IS 'Initial start date and time of call - UTC timestamp'
/
COMMENT ON COLUMN UDR_ST_CRLP.INITIAL_START_TIME_TIME_OFFSET IS 'Initial start date and time of call - Time offset'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_DELIV_HORIZONTAL_ACCUR IS 'Delivered LCS QoS - Horizontal accuracy for an LCS request'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_DELIV_TRACKING_FREQUEN IS 'Delivered LCS QoS - Time (sec) between consecutive location'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_DELIV_TRACKING_PERIOD IS 'Delivered LCS QoS - Overall tracking period measured in sec'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_DELIV_VERTICAL_ACCUR IS 'Delivered LCS QoS - Vertical accuracy for an LCS request'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_INFO_AGE_OF_LOCATION IS 'LCS QoS Information - Actuality of location information'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_INFO_POSITION_METHOD IS 'LCS QoS Information - Handheld position method'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_INFO_RESPONSE_TIME IS 'LCS QoS Information - Actual response time'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_INFO_RESPONSE_TIME_CAT IS 'LCS QoS Information - Response time category'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_REQ_HORIZONTAL_ACCUR IS 'Requested LCS QoS - Horizontal accuracy for an LCS request'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_REQ_TRACKING_FREQUENCY IS 'Requested LCS QoS - Time (sec) between consecutive location'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_REQ_TRACKING_PERIOD IS 'Requested LCS QoS - Overall tracking period measured in sec'
/
COMMENT ON COLUMN UDR_ST_CRLP.LCS_QOS_REQ_VERTICAL_ACCUR IS 'Requested LCS QoS - Vertical accuracy for an LCS request'
/
COMMENT ON COLUMN UDR_ST_CRLP.LDC_INFO_CARRIER_CODE IS 'Long distance carrier (LDC) information - Carrier code'
/
COMMENT ON COLUMN UDR_ST_CRLP.LDC_INFO_CONTRACT_PKEY IS 'Long distance carrier (LDC) information - Contract public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.LDC_INFO_HOME_NET_IND IS 'Long distance carrier (LDC) information - Home network indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.LEC_INFO_CONTRACT_PKEY IS 'Local exchange carrier information - Contract public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.LEC_INFO_HOME_NET_IND IS 'Local exchange carrier information - Home network indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.LZLIST IS 'Logical zones - Logical zone code list'
/
COMMENT ON COLUMN UDR_ST_CRLP.MC_INFO_CODE IS 'Microcell information - Microcell code'
/
COMMENT ON COLUMN UDR_ST_CRLP.MC_INFO_IND IS 'Microcell information - Microcell indicator of rated party'
/
COMMENT ON COLUMN UDR_ST_CRLP.MC_INFO_MICRO_CELL_INFORMATION IS 'Microcell information - FAF indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.MC_SCALEFACTOR IS 'Microcell scale - Scaling factor (% of contracted charge)'
/
COMMENT ON COLUMN UDR_ST_CRLP.MESSAGES_UMCODE IS 'Call messages - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.MESSAGES_VOLUME IS 'Call messages - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.MICRO_CELL_IMCSCALEFACTORTYPE IS 'Micro cell - Individual micro cell scale factor type'
/
COMMENT ON COLUMN UDR_ST_CRLP.MICRO_CELL_MC_CODE IS 'Micro cell - Microcell code'
/
COMMENT ON COLUMN UDR_ST_CRLP.MICRO_CELL_MC_PKEY IS 'Micro cell - Microcell public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.MICRO_CELL_MC_TYPE IS 'Micro cell - Micro cell type'
/
COMMENT ON COLUMN UDR_ST_CRLP.MICRO_CELL_SCALEFACTOR IS 'Micro cell - Scaling factor (% of contracted charge)'
/
COMMENT ON COLUMN UDR_ST_CRLP.NETWORK_INIT_CONTEXT_IND IS 'Call type information - Network-initiated context indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.NET_ELEMENT_HOME_BID_ID IS 'Network element - Home billing ID'
/
COMMENT ON COLUMN UDR_ST_CRLP.NET_ELEMENT_NETWORK_CODE IS 'Network element - Hosting network code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NET_ELEMENT_NETW_ELEMENT_ID IS 'Network element - Network element identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.NET_ELEMENT_USER_PROFILE_ID IS 'Network element - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMED_NET_ELEM_ADDRESS IS 'Normalized network element - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMED_NET_ELEM_INT_ACC_CODE IS 'Normalized network element - International access code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMED_NET_ELEM_NUMBER_PLAN IS 'Normalized network element - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMED_RTD_NUM_ADDRESS IS 'Normalized routed no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMED_RTD_NUM_INT_ACC_CODE IS 'Normalized routed no. - International access code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMED_RTD_NUM_NUMBER_PLAN IS 'Normalized routed no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMTRKGRP_IN_ADDRESS IS 'Normed in-trunk group - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMTRKGRP_IN_NUMBERINGPLAN IS 'Normed in-trunk group - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMTRKGRP_OUT_ADDRESS IS 'Normed out-trunk group - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.NORMTRKGRP_OUT_NUMBERINGPLAN IS 'Normed out-trunk group - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NUMBER_OF_REJECTIONS IS 'Rejection information - No. of rejections'
/
COMMENT ON COLUMN UDR_ST_CRLP.OFFER_OFFER_SEQNO IS 'Offer - Offer sequence no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.OFFER_OFFER_SNCODE IS 'Offer - Offer service name code'
/
COMMENT ON COLUMN UDR_ST_CRLP.ORIGIN_FIELD_ID IS 'UDR field used as origin - UDR field identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.ORIG_ENTRY_DATE_TIMESTAMP IS 'Original entry date timstamp - UTC timestamp'
/
COMMENT ON COLUMN UDR_ST_CRLP.ORIG_ENTRY_DATE_TIMEZONE_ID IS 'Original entry date timstamp - Time zone ID'
/
COMMENT ON COLUMN UDR_ST_CRLP.ORIG_ENTRY_DATE_TIMEZONE_PKEY IS 'Original entry date timstamp - Time zone public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.ORIG_ENTRY_DATE_TIME_OFFSET IS 'Original entry date timstamp - Time offset'
/
COMMENT ON COLUMN UDR_ST_CRLP.OR_FLAG IS 'Optimal routing indicator - Optimal routing indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NORMED_NUM_ADDRESS IS 'Normalized other party no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NORMED_NUM_INT_ACC_CODE IS 'Normalized other party no. - International access code'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NORMED_NUM_NUMBER_PLAN IS 'Normalized other party no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_ADDRESS IS 'Other party no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_BACKUP_ADDRESS IS 'Backup other party no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_CARRIER_CODE IS 'Other party no. - Carrier code'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_CLIR IS 'Other party no. - Calling line identifier restriction'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_NUMBERING_PLAN IS 'Other party no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_OTHER_LOCATION IS 'Other party no. - Other location'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_TYPE_OF_NUMBER IS 'Other party no. - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_NUMBER_USER_PROFILE_ID IS 'Other party no. - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_PUBID_ADDRESS IS 'Other Party Public User ID - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_PUBID_NUMBERING_PLAN IS 'Other Party Public User ID - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.O_P_PUBID_TYPE_OF_NUMBER IS 'Other Party Public User ID - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.PRICE_PLAN_INFO_CHRGPLANID IS 'Price plan information - Charge plan public identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.PRICE_PLAN_INFO_EVALQUANTITY IS 'Price plan information - Evaluation quantity'
/
COMMENT ON COLUMN UDR_ST_CRLP.PRICE_PLAN_INFO_THRESHOLD IS 'Price plan information - Threshold value'
/
COMMENT ON COLUMN UDR_ST_CRLP.PROGRAM_ID IS 'Product description - Program identification code'
/
COMMENT ON COLUMN UDR_ST_CRLP.PROGRAM_NAME IS 'Product description - Program name'
/
COMMENT ON COLUMN UDR_ST_CRLP.PROMO_INFO_B_NUMBER_CAT IS 'Promotion information - Special promo. no. category identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_NEGOT_DELAY IS 'Negotiated quality of service - Delay'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_NEGOT_MEAN_THROUGHPUT IS 'Negotiated quality of service - Mean throughput'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_NEGOT_PEAK_THROUGHPUT IS 'Negotiated quality of service - Peak throughput'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_NEGOT_PRECEDENCE IS 'Negotiated quality of service - Precedence'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_NEGOT_RELIABILITY IS 'Negotiated quality of service - Reliability'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_PROFILE IS 'Quality of service profile - Quality of service profile'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_REQ_DELAY IS 'Requested quality of service - Delay'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_REQ_MEAN_THROUGHPUT IS 'Requested quality of service - Mean throughput'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_REQ_PEAK_THROUGHPUT IS 'Requested quality of service - Peak throughput'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_REQ_PRECEDENCE IS 'Requested quality of service - Precedence'
/
COMMENT ON COLUMN UDR_ST_CRLP.QOS_REQ_RELIABILITY IS 'Requested quality of service - Reliability'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_CLICKS_UMCODE IS 'Rated clicks - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_CLICKS_VOLUME IS 'Rated clicks - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMNT_GROSS_IND_NRPC IS 'Rated flat amount in home currency - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMNT_ORIG_CURRENCY IS 'Original rated flat amount - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMNT_ORIG_GROSS_IND IS 'Original rated flat amount - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMNT_TAX_NRPC IS 'Rated flat amount in home currency - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT IS 'Rated flat amount - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_CURRENCY IS 'Rated flat amount - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_GROSS_IND IS 'Rated flat amount - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_NON_RPC IS 'Rated flat amount in home currency - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_NON_RPC_CURR IS 'Rated flat amount in home currency - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_ORIG_AMOUNT IS 'Original rated flat amount - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_ORIG_TAX IS 'Original rated flat amount - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_TAX IS 'Rated flat amount - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_VOLUME IS 'Rated volume - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_VOLUME_UMCODE IS 'Rated volume - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECIPIENT_NET_ADDRESS IS 'Recipient Network - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECIPIENT_NET_NUMBERING_PLAN IS 'Recipient Network - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_CALL_ID IS 'Record identifier - Call identifier as delivered from CDR'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_CDR_ID IS 'Record identifier - Internal CDR identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_CDR_SUB_ID IS 'Record identifier - Internal CDR subidentifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_EVENT_REF IS 'Record identifier - Event Reference'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_ORIG_CDR_ID IS 'Record identifier - Sequence no. of original CDR'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_RAP_SEQUENCE_NUM IS 'Record identifier - RAP file sequence no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_RERATE_SEQNO IS 'Record identifier - Re-rate sequence no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_SHAACC_UNIQUE_ID IS 'Record identifier - Shared account unique identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_TAP_SEQUENCE_NUM IS 'Record identifier - TAP file sequence no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_ID_UDR_FILE_ID IS 'Record identifier - UDR file identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_TYPE_RECORD_CATEGORY IS 'Record Type - Record category'
/
COMMENT ON COLUMN UDR_ST_CRLP.RECORD_TYPE_SUMMARY_IND IS 'Record Type - Summary indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.REFER_CONTR_CONTRACT_ID IS 'Reference contract - Contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.REFER_CONTR_REFERENCE_TYPE IS 'Reference contract - Reference type'
/
COMMENT ON COLUMN UDR_ST_CRLP.REJECTED_BASE_PART IS 'Rejection information - Rejected base part identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.REJECT_REASON_CODE IS 'Rejection information - Reason for call record rejection'
/
COMMENT ON COLUMN UDR_ST_CRLP.REMARK IS 'Call remark (e.g. VAS information) - Call remark'
/
COMMENT ON COLUMN UDR_ST_CRLP.RERATE_INFO_RERATE_REASON_ID IS 'Re-rate information - Re-rate reason identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.RERATE_INFO_RERATE_RECORD_TYPE IS 'Re-rate information - Re-rate record type'
/
COMMENT ON COLUMN UDR_ST_CRLP.RERATE_INFO_RERATE_REQUEST_ID IS 'Re-rate information - Re-rate request identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.RERATE_INFO_URH_ID IS 'Re-rate information - URH identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUNDED_VOLUME IS 'Rounded rated volume - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUNDED_VOLUME_UMCODE IS 'Rounded rated volume - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUTING_NETWORK_CODE IS 'Routing no. - Hosting network code'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUTING_NUMBER_BACKUP_ADDRESS IS 'Backup routing no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUTING_USER_PROFILE_ID IS 'Routing no. - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.SCU_ID_ADDRESS IS 'Service center identifier - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.SCU_ID_USER_PROFILE_ID IS 'Service center identifier - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.SCU_INFO_PRIORITY_CODE IS 'Service center usage information - Priority code for service center usage'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_ACTION_CODE IS 'Service - Action code for supplementary services'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_GUARANTEED_BIT_RATE IS 'Service - Guaranteed bit rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_HSCSD_IND IS 'Service - HSCSD indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_IMS_SIGNALLING_CONTEXT IS 'Service - IMS signalling content'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_LOGIC_CODE IS 'Service - Service logic code'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_MAX_BIT_RATE IS 'Service - Maximal bit rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_SERVICE_TYPE IS 'Service - Type of Service'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_USED_SERVICE IS 'Service - Internal identifier of service used'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_USER_PROTOCOL_IND IS 'Service - User protocol indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERVICE_VAS_CODE IS 'Service - Value-added service code'
/
COMMENT ON COLUMN UDR_ST_CRLP.SERV_PDP_ADDR_APN_SPLIT_IND IS 'PDP address of served IMSI - Access Point Name splitting supported'
/
COMMENT ON COLUMN UDR_ST_CRLP.SGSN_ADDRESSES IS 'IP address of SGSN - SGSN addresses'
/
COMMENT ON COLUMN UDR_ST_CRLP.SPEC_NUM_INFO_APPLY_FREE_UNITS IS 'Special no. information - Free units application indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.START_TIME_CHARGE_OFFSET IS 'Start date and time for charge - Time offset'
/
COMMENT ON COLUMN UDR_ST_CRLP.START_TIME_CHARGE_TIMESTAMP IS 'Start date and time for charge - UTC timestamp'
/
COMMENT ON COLUMN UDR_ST_CRLP.START_TIME_OFFSET IS 'Start date and time of call - Time offset'
/
COMMENT ON COLUMN UDR_ST_CRLP.START_TIME_TIMESTAMP IS 'Start date and time of call - UTC timestamp'
/
COMMENT ON COLUMN UDR_ST_CRLP.SUM_REFERENCE_SINGLE_ID IS 'Summary reference type - Single record identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_ADDRESS IS 'PDP address of served IMSI - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_CARRIER_CODE IS 'PDP address of served IMSI - Carrier code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_CLIR IS 'PDP address of served IMSI - Calling line identifier restriction'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_INTERN_ACCESS_CODE IS 'PDP address of served IMSI - International access code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_MODIFICATION_IND IS 'PDP address of served IMSI - Modification indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_NETWORK_CODE IS 'PDP address of served IMSI - Hosting network code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_NUMBERING_PLAN IS 'PDP address of served IMSI - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_TYPE_OF_NUMBER IS 'PDP address of served IMSI - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_PDP_USER_PROFILE_ID IS 'PDP address of served IMSI - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_EQUIPMENT_CLASS_MARK IS 'Served party IMEI - Mobile class mark'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_EQUIPMENT_NUMBER IS 'Served party IMEI - Equipment no.'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_HOME_ID_DESCRIPTION IS 'Charged Party Home Identification - Description'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_HOME_ID_HOME_BID_ID IS 'Charged Party Home Identification - Home billing ID'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_HOME_ID_NAME IS 'Charged Party Home Identification - Name'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_HOME_ID_NETWORK IS 'Charged Party Home Identification - Network string'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_HOME_LOC_ADDRESS IS 'Served party home location - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_HOME_LOC_NUMBERING_PLAN IS 'Served party home location - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_LOCATION_ADDRESS IS 'Served party location - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_LOCATION_NUMBERING_PLAN IS 'Served party location - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_LOC_SERVING_BID_ID IS 'Served party location - Serving BID ID'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_LOC_SERVING_LOCATION IS 'Served party location - Serving location'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_NUMBER_ADDRESS IS 'Served party directory no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_NUMBER_HOME_BID_ID IS 'Served party directory no. - Home billing ID'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_NUMBER_NETWORK_CODE IS 'Served party directory no. - Hosting network code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_NUMBER_NUMBERING_PLAN IS 'Served party directory no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_NUMBER_USER_PROFILE_ID IS 'Served party directory no. - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_PORT_ADDRESS IS 'Served party port no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_PORT_NUMBERING_PLAN IS 'Served party port no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.S_P_PORT_USER_PROFILE_ID IS 'Served party port no. - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_CHGBL_QUANTITY IS 'Detailed tariff information - Chargeable quantity (basis for charge)'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_EXT_CHRG_UDMCODE IS 'Detailed tariff information - External charge member code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_INTERCONNECT_IND IS 'Detailed tariff information - Interconnect rate type indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_RATE_TYPE_ID IS 'Detailed tariff information - Rate type identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_RTX_CHARGE_TYPE IS 'Detailed tariff information - RTX charge type'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_TTCODE IS 'Detailed tariff information - Tariff time code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_CATALOGUE_ID IS 'Common tariff information - Catalogue identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_CATALOGUE_VERS IS 'Common tariff information - Catalogue version'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_CTLG_ELM_ID IS 'Common tariff information - Catalogue Element identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_EGCODE IS 'Common tariff information - Extended GL code package code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_EGVERSION IS 'Common tariff information - Extended GL code package version'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_GVCODE IS 'Common tariff information - Zone coverage code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_PRICELIST_ID IS 'Common tariff information - Pricelist identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_PRICELIST_PKEY IS 'Common tariff information - Pricelist public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_PRICELIST_VERS IS 'Common tariff information - Pricelist version'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_PRICE_DEF_VERS IS 'Common tariff information - Price Definition version'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_RPCODE IS 'Common tariff information - Rating package code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_RPVERSION IS 'Common tariff information - Rating package version'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_SNCODE IS 'Common tariff information - Service name code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_SPCODE IS 'Common tariff information - Service package code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_TIME_BAND_CODE IS 'Common tariff information - Time band code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_TMCODE IS 'Common tariff information - Rate plan'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_TMVERSION IS 'Common tariff information - Rate plan version'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_TM_USED_TYPE IS 'Common tariff information - Type of rate plan used for rating'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_TWCODE IS 'Common tariff information - Tariff week code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_USAGE_IND IS 'Common tariff information - Usage indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_ZNCODE IS 'Common tariff information - Tariff zone code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_ZPCODE IS 'Common tariff information - Terminating zonal point code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_INFO_ZPCODE_DAY_CATCODE IS 'Common tariff information - Day category code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TAX_INFO_SERV_CAT IS 'Tax information - Service category'
/
COMMENT ON COLUMN UDR_ST_CRLP.TAX_INFO_SERV_CODE IS 'Tax information - Service code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TAX_INFO_SERV_TYPE IS 'Tax information - Service type'
/
COMMENT ON COLUMN UDR_ST_CRLP.TECHN_INFO_FIXED_MOBILE_IND IS 'Technical call information - Indicator for fixed or mobile usage'
/
COMMENT ON COLUMN UDR_ST_CRLP.TECHN_INFO_HOME_TERMINATED_IND IS 'Technical call information - Call termination in HPLMN indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.TECHN_INFO_PREPAY_IND IS 'Technical call information - Prepaid/postpaid indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.TECHN_INFO_PRE_RATED_IND IS 'Technical call information - Prerating indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.TECHN_INFO_REV_CHARGING_IND IS 'Technical call information - Reverse charging indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.TECHN_INFO_SCCODE IS 'Technical call information - Market'
/
COMMENT ON COLUMN UDR_ST_CRLP.TECHN_INFO_TERMINATION_IND IS 'Technical call information - Call termination indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.TRUNK_GROUP_IN_ADDRESS IS 'In-trunk group - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.TRUNK_GROUP_IN_NUMBERINGPLAN IS 'In-trunk group - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TRUNK_GROUP_IN_TYPEOFNUMBER IS 'In-trunk group - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.TRUNK_GROUP_OUT_ADDRESS IS 'Out-trunk group - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.TRUNK_GROUP_OUT_NUMBERINGPLAN IS 'Out-trunk group - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.TRUNK_GROUP_OUT_TYPEOFNUMBER IS 'Out-trunk group - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.T_P_NUMBER_USER_PROFILE_ID IS 'Third party no. - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDR_BASEPART_ID IS 'Base part identifier - UDR base part identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDR_CHARGEPART_ID IS 'Charge part identifier - UDR charge part identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDS_BASE_PART_ID IS 'Base Part'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDS_CHARGE_PART_ID IS 'Charge Part'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDS_FREE_UNIT_PART_ID IS 'Free Units Part'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDS_PROMOTION_PART_ID IS 'Promotion Part'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDS_RECORD_ID IS 'Usage Data Record'
/
COMMENT ON COLUMN UDR_ST_CRLP.UDS_STREAM_ID IS 'Usage Data Stream Identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_ALLC_RETN_PRIOR IS 'UMTS Negotiated Quality of Service - UMTS QoS allocation retention priority'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_DELAY IS 'UMTS Negotiated Quality of Service - Transfer delay'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_DELIVERY_ORDER IS 'UMTS Negotiated Quality of Service - UMTS QoS delivery order'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_ERRONEOUS_SDUS IS 'UMTS Negotiated Quality of Service - UMTS QoS erroneous SDUs'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_HANDL_PRIORITY IS 'UMTS Negotiated Quality of Service - UMTS QoS handling priority'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_MAX_SIZE_SDU IS 'UMTS Negotiated Quality of Service - UMTS QoS maximum size of SDU'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_RATE_DOWNLINK IS 'UMTS Negotiated Quality of Service - UMTS QoS max. bit rate for incoming data'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_RATE_UPLINK IS 'UMTS Negotiated Quality of Service - UMTS QoS max. bit rate for outgoing data'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_RESIDUAL_BER IS 'UMTS Negotiated Quality of Service - UMTS QoS residual BER'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_SDU_ERR_RATIO IS 'UMTS Negotiated Quality of Service - UMTS QoS SDU error ratio'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_NEGOT_TRAFFIC_CLASS IS 'UMTS Negotiated Quality of Service - UMTS QoS traffic class'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_ALLC_RETN_PRIOR IS 'UMTS Requested Quality of Service - UMTS QoS allocation retention priority'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_DELAY IS 'UMTS Requested Quality of Service - Transfer delay'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_DELIVERY_ORDER IS 'UMTS Requested Quality of Service - UMTS QoS delivery order'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_ERRONEOUS_SDUS IS 'UMTS Requested Quality of Service - UMTS QoS erroneous SDUs'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_HANDL_PRIORITY IS 'UMTS Requested Quality of Service - UMTS QoS handling priority'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_MAX_SIZE_SDU IS 'UMTS Requested Quality of Service - UMTS QoS maximum size of SDU'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_RATE_DOWNLINK IS 'UMTS Requested Quality of Service - UMTS QoS max. bit rate for incoming data'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_RATE_UPLINK IS 'UMTS Requested Quality of Service - UMTS QoS max. bit rate for outgoing data'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_RESIDUAL_BER IS 'UMTS Requested Quality of Service - UMTS QoS residual BER'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_SDU_ERROR_RATIO IS 'UMTS Requested Quality of Service - UMTS QoS SDU error ratio'
/
COMMENT ON COLUMN UDR_ST_CRLP.UMTS_QOS_REQ_TRAFFIC_CLASS IS 'UMTS Requested Quality of Service - UMTS QoS traffic class'
/
COMMENT ON COLUMN UDR_ST_CRLP.UNBILLEDAMTPAYMRESP_CUSTOMERID IS 'Unbilled amount payment responsible - Customer identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.UNBILLED_AMOUNT_AMOUNT IS 'Unbilled amount info determined by RLH - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.UNBILLED_AMOUNT_CURRENCY IS 'Unbilled amount info determined by RLH - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.UNBILLED_AMOUNT_GROSS_IND IS 'Unbilled amount info determined by RLH - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.UNBILLED_AMOUNT_TAX IS 'Unbilled amount info determined by RLH - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.UPLINK_VOLUME_UMCODE IS 'Uplink data volume - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.UPLINK_VOLUME_VOLUME IS 'Uplink data volume - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_INFO_VPN_CALL_TYPE IS 'VPN information - VPN call type'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_ADDRESS IS 'VPN no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_CARRIER_CODE IS 'VPN no. - Carrier code'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_CLIR IS 'VPN no. - Calling line identifier restriction'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_DYNAMIC_ADDRESS IS 'VPN no. - Dynamic address indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_INT_ACCESS_CODE IS 'VPN no. - International access code'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_LOCAL_PREFIX_LEN IS 'VPN no. - Length of the local prefix'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_MODIFICATION_IND IS 'VPN no. - Modification indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_NETWORK_CODE IS 'VPN no. - Hosting network code'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_NUMBERING_PLAN IS 'VPN no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_TYPE_OF_NUMBER IS 'VPN no. - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.VPN_NUMBER_USER_PROFILE_ID IS 'VPN no. - User profile identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_BASE_CHARGE_AMOUNT IS 'Exchange file base charge - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_BASE_CHARGE_CURRENCY IS 'Exchange file base charge - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_BASE_CHARGE_GROSS_IND IS 'Exchange file base charge - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_BASE_CHARGE_TAX IS 'Exchange file base charge - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_CALL_TYPE IS 'Call type information - TAP call type configuration indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_CHARGE_AMOUNT IS 'Exchange file charge - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_CHARGE_CURRENCY IS 'Exchange file charge - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_CHARGE_GROSS_IND IS 'Exchange file charge - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_CHARGE_TAX IS 'Exchange file charge - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_DAY_CATEGORY_CODE IS 'Exchange file tariff information - Day category code'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_DISCOUNT_AMOUNT IS 'Discount value from TAP file (TD.57) - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_DISCOUNT_CURRENCY IS 'Discount value from TAP file (TD.57) - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_IC_CHARGE_AMOUNT IS 'Exchange file interconnect charge - Monetary amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_IC_CHARGE_CURRENCY IS 'Exchange file interconnect charge - Currency'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_IC_CHARGE_GROSS_IND IS 'Exchange file interconnect charge - Gross amount indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_IC_CHARGE_TAX IS 'Exchange file interconnect charge - Tax rate'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_IND IS 'Call type information - Exchange file indicator'
/
COMMENT ON COLUMN UDR_ST_CRLP.XFILE_TIME_BAND_CODE IS 'Exchange file tariff information - Time band code'
/
COMMENT ON COLUMN UDR_ST_CRLP.ZERO_RATED_VOLUME_UMCODE IS 'Zero charged rated volume - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.ZERO_RATED_VOLUME_VOLUME IS 'Zero charged rated volume - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.ZERO_ROUNDED_VOLUME_UMCODE IS 'Zero charged rounded volume - Unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.ZERO_ROUNDED_VOLUME_VOLUME IS 'Zero charged rounded volume - Volume in unit of measure'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_VALID_FROM IS 'Balance audit data - Start date'
/
COMMENT ON COLUMN UDR_ST_CRLP.BAL_AUDIT_DAT_VALID_TO IS 'Balance audit data - End date'
/
COMMENT ON COLUMN UDR_ST_CRLP.CHRGAGGRINFO_REQUEST_ID IS 'Charge aggregation information - Request identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_CUSTOMER_GROUP IS 'Customer information of charged party - Customer group'
/
COMMENT ON COLUMN UDR_ST_CRLP.CUST_INFO_PARENT_CONTRACT_ID IS 'Customer information of charged party - Parent contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY1_PARENT_CONTRACT_ID IS 'Customer information of impacted party 1 - Parent contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY2_PARENT_CONTRACT_ID IS 'Customer information of impacted party 2 - Parent contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.IMP_PARTY3_PARENT_CONTRACT_ID IS 'Customer information of impacted party 3 - Parent contract identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.NET_ELEMENT_ADDRESS IS 'Network element - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.NET_ELEMENT_NUMBERING_PLAN IS 'Network element - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.NET_ELEMENT_TYPE_OF_NUMBER IS 'Network element - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMNT_ORIG_DISC_AMNT IS 'Original rated flat amount - Discounted amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.RATED_FLAT_AMOUNT_DISC_AMOUNT IS 'Rated flat amount - Discounted amount'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUTING_ADDRESS IS 'Routing no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUTING_NUMBERING_PLAN IS 'Routing no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.ROUTING_TYPE_OF_NUMBER IS 'Routing no. - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_PRICGALTERNPKEY IS 'Detailed tariff information - Pricing alternative public key'
/
COMMENT ON COLUMN UDR_ST_CRLP.TARIFF_DETAIL_PRICINGALTERNID IS 'Detailed tariff information - Pricing alternative identifier'
/
COMMENT ON COLUMN UDR_ST_CRLP.T_P_NUMBER_ADDRESS IS 'Third party no. - Address string'
/
COMMENT ON COLUMN UDR_ST_CRLP.T_P_NUMBER_NUMBERING_PLAN IS 'Third party no. - Numbering plan code'
/
COMMENT ON COLUMN UDR_ST_CRLP.T_P_NUMBER_TYPE_OF_NUMBER IS 'Third party no. - Type of number'
/
COMMENT ON COLUMN UDR_ST_CRLP.UNBILLED_AMOUNT_BILLING_ACC IS 'Unbilled amount info determined by RLH - Rated Amount Charge for Billing Account'
/
COMMENT ON COLUMN UDR_ST_CRLP.UNBILLED_AMOUNT_COMPL_COND_ID IS 'Unbilled amount info determined by RLH - Complex Condition Billing Account'
/
CALL DabUtil.CreateSynonym ('PUBLIC','UDR_ST_CRLP')
/
CALL DabUtil.GrantPriv('UDR_ST_CRLP','BSCS_ROLE','SELECT','UPDATE','INSERT','DELETE')
/
